### ISSUE TITLE
Example WebRTC client implementation

### ISSUE THREAD

**Issue by huaiyizhao** [bengreenier/node-dss#17]
Hello, @bengreenier. Can you give a minimal example of two WebRTC clients using this signal server to communicate? Thank you.

**Comment by bengreenier** [comment]
Hi @huaiyizhao - I don’t recommend using this anymore, it is quite old. That said, there is https://github.com/bengreenier/webrtc-unity-plugin which mentions what using this project for signaling would be like.

**Comment by huaiyizhao** [comment]
Thank you @bengreenier. I know this is an old repo, but I'm currently playing around with Mixed-Reality WebRTC on HoloLens 2 (even though deprecated but there seems no replacement on the market right now) and it depends on this signal server. I can make two clients talk to each other if I follow the instructions and build my apps on Unity. However, I need one client to be a program that runs on a Linux server and does some processing. So basically I have two options. 1) Find a working example of a WebRTC client and a signaling server in Linux, and modify some code in the Mixed-Reality WebRTC demo client to make it compatible with the former two. But I believe this modification is not easy since some code is pre-compiled as a Unity package. 2) Stick with the  Mixed-Reality WebRTC demo client implementation and **THIS**  signaling server, and write another Linux client that is compatible with these two. This is a promising approach I think, but I have to solve the problem of creating such a Linux client, or somehow make the demo client work on Linux without graphics (I know Unity can set build settings to Linux standalone but I'm not looking into it yet.) So, what will you do in such a scenario? Any advice? Thanks in advance.

**Comment by bengreenier** [comment]
If you're looking for a production-quality solution i'd add a custom signaling implementation to go with Mixed-Reality WebRTC - you will not need to modify any of the native code to do so - only re-implement [Signaler](https://github.com/microsoft/MixedReality-WebRTC/blob/master/libs/unity/library/Runtime/Scripts/Signaling/Signaler.cs) -in fact, just two methods (the ones in [this pragma block](https://github.com/microsoft/MixedReality-WebRTC/blob/master/libs/unity/library/Runtime/Scripts/Signaling/Signaler.cs#L29)).

You can see the one I implemented for NodeDSS as a starting point: https://github.com/microsoft/MixedReality-WebRTC/blob/master/libs/unity/library/Runtime/Scripts/Signaling/NodeDssSignaler.cs

That said, if you don't need production quality, then yeah you can just use this project (it's just dependencies are very old, haven't tested with new versions of node, etc).

**Comment by huaiyizhao** [comment]
We do not need production quality so sticking to this project is OK. Npm complains about some broken packages but it works fine. So basically I need to write a signaler compatible with this signal server in my remote side client (since it is a Linux application that does some processing on the received video stream, and I doubt the Unity packages are functional in Linux out-of-the-box). I finally choose Python and `aiortc` library to do the job, and now all I need to do is grab a demo WebRTC client from `aiortc` examples and add a signaler to it following your implementation in C# (https://github.com/microsoft/MixedReality-WebRTC/blob/master/libs/unity/library/Runtime/Scripts/Signaling/NodeDssSignaler.cs). Any chance you have a working Python client example already :)

**Comment by bengreenier** [comment]
No python example is available - sorry.
